trailingComma: es5
tabWidth: 2
semi: true
singleQuote: false
arrowParens: always
overrides:
  - files: "*.sol"
    options:
      printWidth: 160
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: true
      explicitTypes: always
